### ISSUE TITLE
Comment actually

### ISSUE THREAD

**Issue by atiqsu** [WP-Plugin-Master/PluginMaster#1]
Hi, 

On `index.php:35 `- you have declared `global `variable; so if two plugin is made out of this framework and installed wouldn't collide/overwrite the value?

Looks nice to me, hope I will use it.

**Comment by emrancu** [comment]
Many thanks Dear,
I will solve the issue as soon as possible.

**Comment by emrancu** [comment]
Thanks a lot for informing.
I will solve as soon as possibl.  ❤

**Comment by emrancu** [comment]
Dear @atiqsu , Global Variable issue solved. Please have a look.
