### ISSUE TITLE
Plugin Activation 

### ISSUE THREAD

**Issue by pioneersingh321** [WP-Plugin-Master/PluginMaster#15]
The plugin generated 1 character of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

with this error WordPress ajax functions are not working properly 
cant add category
cant add tags

its generation one extra space in ajax response

**Comment by pioneersingh321** [comment]
after some research i have found that on plugin file 
like my plugin name is myplugin then in myplugin.php file
in top from where code start there is one space and then php code is starting 

remove that empty space on from that file

**Comment by emrancu** [comment]
@pioneersingh321  Thank You for informing. 

We will release  production ready version soon. Tomorrow will release beta version.
