### ISSUE TITLE
A lot of interfaces issue when enabling plugin with generator

### ISSUE THREAD

**Issue by iniznet** [WP-Plugin-Master/PluginMaster#17]
Enabling plugin that generated by site generator,
![image](https://user-images.githubusercontent.com/34362833/183139401-87b45e66-ec0f-444a-ac53-d545c22a8d88.png)

I tried to use the latest commit but not quite can be used either,
![image](https://user-images.githubusercontent.com/34362833/183138153-0ddbee7e-6805-4185-93f3-25a011e6d07c.png)

Is there any commit after 1.0.8 that can run the plugin without figuring any error? or I should try the 1.0.7 release instead?

Sage 10 & PHP 8.0.

**Comment by emrancu** [comment]
@iniznet  Thank You for informing.

We will release production ready version soon. Tomorrow will release beta version with support php7.4 to up.
